services:
  # PostgreSQL Database for Application
  postgres:
    image: postgres:16-alpine
    container_name: test-graviola-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-test}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test123}
      POSTGRES_DB: ${POSTGRES_DB:-test}
    ports:
      - "${POSTGRES_PORT:-5434}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-ausleihsystem}"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:
    name: test-graviola-postgres