name: Graviola - Publish NPM packages

on:
  release:
    types: [created, published]
  # Trigger via 'Actions' on GitHub
  workflow_dispatch:


jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.bun }}-bun-
      - run: bun i
      - run: bun build:packages
      - name: Configure npm authentication
        run: |
          echo "@graviola:registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
      - name: Publish packages
        run: bun run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}